// <auto-generated />
namespace Ecommerce_Vestuario_REVIEW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablesAccessoriesandshoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablesAccessoriesandshoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201712012125559_tables-Accessories-and-shoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
